from .cosplace import CosPlace
from .convap import ConvAP
from .gem import GeMPool
from .gem_dino import GeMPoolDino
from .mixvpr import MixVPR
from .salad import SALAD
from .crica import Crica
from .he_salad import HE_SALAD
from .transvpr import POOL